from playwright.sync_api import Page
def test_example(page: Page) -> None:
    page.goto("http://localhost:5173/")

    page.get_by_role("link", name="Login").click()
    page.get_by_label("Email").click()
    page.get_by_label("Email").fill("testmail@test.com")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("Test098_")
    page.get_by_role("button", name="Login").click()
    page.get_by_placeholder("Enter your blog title here").click()
    page.get_by_placeholder("Enter your blog title here").fill("Test Blog")
    page.get_by_placeholder("Write your blog content here").click()
    page.get_by_placeholder("Write your blog content here").fill("Testing a blog")
    page.get_by_placeholder("Tags").click()
    page.get_by_placeholder("Tags").fill("Testing")
    page.get_by_role("button", name="Publish").click()
    page.get_by_role("link", name="Test Blog").click()
    page.get_by_role("link", name="Edit").click()
    page.get_by_label("Title").click()
    page.get_by_label("Title").fill("Test Blog Edit")
    page.get_by_label("Content").click()
    page.get_by_label("Content").fill("Testing a blog Edit")
    page.get_by_role("button", name="Save Changes").click()
    page.get_by_role("link", name="Back to Dashboard").click()
    page.get_by_role("link", name="Test Blog Edit").click()
    page.get_by_role("button", name="Delete").click()
    page.get_by_text("No blogs yet").click()
    page.get_by_role("button", name="Logout").click()
